"""initial schema

Revision ID: eb46fdd26fc3
Revises: 
Create Date: 2026-08-24 08:54:15.931653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb46fdd26fc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cause_of_actions',
    sa.Column('cause_of_action_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cause_of_action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cause_of_action_id'),
    sa.UniqueConstraint('cause_of_action')
    )
    op.create_table('companies_reference',
    sa.Column('company_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('complainants',
    sa.Column('complainant_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('complainant_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'handling_personnel', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.Enum('Filed', 'Pending', 'Execution', 'Closed', name='casestatus'), nullable=False),
    sa.Column('last_status_update', sa.Date(), nullable=True),
    sa.Column('case_title', sa.String(length=255), nullable=False),
    sa.Column('case_no', sa.String(length=100), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('handling_personnel', sa.String(length=150), nullable=True),
    sa.Column('handling_personnel_specification', sa.String(length=255), nullable=True),
    sa.Column('cause_specification', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Enum('Settled', 'Not_Settled', 'Others', name='stageprogress'), nullable=True),
    sa.Column('remark_specification', sa.String(length=500), nullable=True),
    sa.Column('total_paid_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_paid_category', sa.Enum('Judgment_Award_L', 'Judgment_Award_W', 'Settlement', name='totalpaidcategory'), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_username', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_username', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies_reference.company_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_case_no'), 'cases', ['case_no'], unique=True)
    op.create_table('case_causes',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('cause_of_action_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['cause_of_action_id'], ['cause_of_actions.cause_of_action_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'cause_of_action_id')
    )
    op.create_table('case_complainants',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('complainant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['complainant_id'], ['complainants.complainant_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'complainant_id')
    )
    op.create_table('case_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('case_no', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('created', 'updated', 'archived', 'restored', name='casehistoryaction'), nullable=False),
    sa.Column('performed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('performed_by_username', sa.String(length=150), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('decisions',
    sa.Column('decision_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Enum('labor_arbiter', 'national_labor_relations_commission', 'court_of_appeals', 'supreme_court', name='decisionlevel'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Valid_Dismissal', 'Illegal_Dismissal', 'Convicted', 'Acquitted', 'Dismissed', 'Affirmed', 'Pending', 'Closed', 'Execution', name='tribunaldecisionstatus'), nullable=True),
    sa.Column('judgment_award_mode', sa.Enum('amount', 'to_be_computed', name='judgmentawardmode'), nullable=True),
    sa.Column('judgment_award_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('judgment_award_amount_specification', sa.String(length=500), nullable=True),
    sa.Column('judgment_award_computed_specification', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Enum('Appealed_by_Respondent', 'Appealed_by_Complainant', 'Not_Appealed', 'Other', name='tribunalremarks'), nullable=True),
    sa.Column('remarks_specification', sa.String(length=500), nullable=True),
    sa.Column('progress', sa.Enum('Settled', 'Not_Settled', 'Others', name='stageprogress'), nullable=True),
    sa.Column('progress_specification', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('case_id', 'level', name='uq_case_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_table('case_history')
    op.drop_table('case_complainants')
    op.drop_table('case_causes')
    op.drop_index(op.f('ix_cases_case_no'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('complainants')
    op.drop_table('companies_reference')
    op.drop_table('cause_of_actions')
    # ### end Alembic commands ###